language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libboost-filesystem-dev 
  - sudo apt-get install -y libboost-program-options-dev
  - sudo apt-get install -y cmake

before_script:
   - cmake .

script: 
   - make -j4

