build_image: shippableimages/ubuntu1404_python
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get update -qq
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libboost-filesystem-dev 
  - sudo apt-get install -y libboost-program-options-dev
  - sudo apt-get install -y cmake

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

before_script:
   - cmake .

script: 
   - make -j4

