build_image: shippableimages/ubuntu1404_python
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev libboost-test-dev libboost-system-dev libboost-filesystem-dev libboost-log-dev libboost-program-options-dev
  - sudo apt-get install -y cmake


before_script:
   - cmake .

script: 
   - make -j4
   - ctest -VV
